lukepafford_blog/blog/urls.py
from django.urls import path
from .views import HomeView, PostList, PostUpload, PostDetail

urlpatterns = [
    path("", PostList.as_view(), name="posts_list"),
    path("posts/<slug:slug>/", PostDetail.as_view(), name="posts_detail"),
    path("upload/", PostUpload.as_view(), name="posts_upload"),
]

lukepafford_blog/lukepafford_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("manage/", admin.site.urls),
    path("", include("blog.urls")),
]

lukepafford_blog/blog/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django.utils import timezone


class Posts(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)
    body = models.TextField()

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comments(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    commenter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.comment


class Replies(models.Model):
    reply = models.TextField()
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE)
    replier = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.reply


class Tags(models.Model):
    post = models.ManyToManyField(Posts)
    tag = models.TextField()

    def __str__(self):
        return self.tag

lukepafford_blog/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

lukepafford_blog/blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Comments


class UploadPostForm(forms.Form):
    file = forms.FileField()


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ["comment"]

lukepafford_blog/blog/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.base import TemplateView
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from .models import Posts, Comments, Replies
from .forms import UploadPostForm, CommentForm
from .markdown_parser import parse_yaml_post
from .date_conversions import extract_date_from_title


# Create your views here.
class HomeView(TemplateView):
    template_name = "_base.html"


class PostList(ListView):
    model = Posts
    context_object_name = "posts"
    paginate_by = 10


class PostDetail(DetailView):
    model = Posts
    context_object_name = "post"
    queryset = Posts.objects.all()

    def get_queryset(self):
        return self.queryset.filter(slug=self.kwargs.get("slug"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["commentForm"] = CommentForm
        return context

    # update the database from the form on POST
    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = Posts.objects.get(slug=kwargs["slug"])
            comment = form.save(commit=False)
            comment.commenter = request.user
            comment.post = post
            comment.save()
        return redirect(reverse("posts_detail", kwargs={"slug": kwargs["slug"]}))


class PostUpload(LoginRequiredMixin, DetailView):
    def get(self, request):
        form = UploadPostForm
        return render(request, "blog/post_upload.html", {"form": form})

    def post(self, request):
        form = UploadPostForm(request.POST, request.FILES)
        if form.is_valid():
            parsed_data = parse_yaml_post(form.cleaned_data["file"])

            # Don't allow an upload if the name of the post doesn't have
            # the date in the beginning of the filename
            try:
                created_on = extract_date_from_title(request.FILES["file"].name)
            except ValueError as e:
                response = HttpResponse(e)
                response.status_code = 422
                return response

            # Overwrite existing post if title is the same
            try:
                post = Posts.objects.get(title=parsed_data["title"])
            except Posts.DoesNotExist:
                post = Posts()

            post.title = parsed_data["title"]
            post.body = parsed_data["body"]
            post.created_on = created_on
            post.author = request.user
            post.save()
        return redirect("posts_list")

lukepafford_blog/user/views.py
from django.shortcuts import render

# Create your views here.

lukepafford_blog/templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|Rubik|Space+Mono&display=swap" rel="stylesheet"> 
		<link rel="stylesheet" href="{% static 'css/base.css' %}">
		<link rel="stylesheet" href="{% static 'css/code_highlight.css' %}">
		<title>lukepafford.com</title>
  </head>
  <body>

<nav class="navbar sticky-top navbar-dark bg-dark justify-content-center">
	<a class="nav-link justify-content-center" href="{% url 'posts_list' %}">lukepafford.com <span class="fa fa-home"></span></a>
</nav>

<!--
<nav class="navbar sticky-top navbar-dark bg-dark justify-content-end">
	<button class="nav-link btn btn-link btn-group btn-group-vertical"><span class="fa fa-bars"></span></button>
</nav>
--!>

	<div class="container">
		{% block content %}
		{% endblock content %}
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<script src="{% static 'js/bundle.js' %}"></script>
  </body>
</html>

lukepafford_blog/templates/blog/blog_list.html
{% extends '_base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}

<h2>Posts</h2>
{% for post in posts %}
	<ul>
		<li>{{ post }}</li>
	</ul>
{% endfor %}

{% endblock content %}

lukepafford_blog/templates/blog/blog_upload.html
{% extends '_base.html' %}

{% block content %}
<h2>Post Upload</h2>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
<button type="submit">Submit</button>
</form>

{% endblock content %}

lukepafford_blog/templates/blog/post_upload.html
{% extends '_base.html' %}

{% block content %}
<h2>Post Upload</h2>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
<button type="submit">Submit</button>
</form>

{% endblock content %}

lukepafford_blog/templates/blog/posts_detail.html
{% extends '_base.html' %}
{% load markdown_deux_tags %}

{% block title %}Posts{% endblock %}

{% block content %}



<h1>{{ post.title }}</h1>
<p>
{{ post.body|markdown }}
</p>

<h1 id="Comments">Comments</h1>

{% if user.is_authenticated %}
<form method="post">
{% csrf_token %}
	<div class="input-group mb-3">
		<input name="{{ commentForm.comment.html_name }}" type="text" class="form-control"  aria-describedby="button-addon2">
		<div class="input-group-append">
			<button class="btn btn-outline-primary" id="button-addon2">Submit</button>
		</div>
	</div>
</form>
{% endif %}

<ul class="list-group">
{% for comment in post.comments_set.all %}
	<li class="list-group-item">{{ comment }}</li>
{% endfor %}
</ul>

{% endblock content %}

lukepafford_blog/templates/blog/posts_list.html
{% extends '_base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}

<h2 class="text-center">Posts</h2>
{% for post in posts %}
	<div class="card text-center">
			<div class="card-body">
				<div class="card-title">
					<h2><a href="{% url 'posts_detail' post.slug %}">{{ post.title }}</a></h2>
				</div>
				<div class="card-footer text-muted">Published {{ post.created_on|date:'Y-m-d' }}</div>
			</div>
		</ul>
	</div>
</ul>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}

lukepafford_blog/templates/posts/post_detail.html
{% extends '_base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
<p>
{{ post.body }}
</p>

{% endblock content %}

lukepafford_blog/templates/posts/post_list.html
{% extends '_base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}

<h2>Posts</h2>
{% for post in posts %}
	<ul>
		<li><a href="{% url 'post_detail' post.pk %}">{{ post }}</a></li>
	</ul>
{% endfor %}

{% endblock content %}